language: go
go: 1.17.x

git:
  submodules: false

sudo: false

before_install:
  - echo "do nothing"

install: true

script:
  - go mod tidy
  - go test ./... -coverprofile=.coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)