language: go
go: 1.17.x

git:
  submodules: false

sudo: false

before_install:
  - COVERAGE_REPORT=.coverage.txt

install: true

script:
  - go mod tidy
  - go test ./... -coverprofile=${COVERAGE_REPORT} -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ${COVERAGE_REPORT} -t ${CODECOV_TOKEN}